from pathlib import Path
import os

# Get the root directory of your project
root_dir = os.path.dirname(os.path.abspath('Map2.py'))

a = Analysis(
    ['Map2.py'],  # Your main script
    pathex=[root_dir],
    binaries=[],
    datas=[
        # Ensure these paths are correctly included
        (os.path.join(root_dir, 'Icons'), 'Icons'),
        (os.path.join(root_dir, 'Palettes'), 'Palettes'),
    ],
    hiddenimports=[
        # GUI
        'PySide6.QtCore',
        'PySide6.QtGui',
        'PySide6.QtWidgets',
        'PySide6.QtCharts',
        'PySide6.QtPrintSupport',
        'PySide6.QtSvg',
        
        # Scientific & Data Processing Packages
        'numpy',
        'pandas',
        'matplotlib',
        'matplotlib.backends.backend_qt5agg',
        'matplotlib.backends.backend_qt5cairo',
        'scipy',
        'seaborn',
        'segyio',
        'shapely',
        'sklearn',
        'statsmodels',
        'pingouin',
        'plotly',
        'mplcursors',
        'openpyxl',
        'ujson',
        'pystray',
        'cryptography',
        'datrie',
        'networkx',
        'certifi',
        'lxml',
        'mpl_toolkits',
        'PyPI',
        'PySide6.QtTest',
        
        # Standard Library Modules (ensure explicit inclusion if needed)
        'queue', 'html', 'http', 'ssl', 'unicodedata',
        'uuid', 'email', 'urllib', 'tkinter', 'pickle', 'bz2', 'sqlite3',
        'pyparsing', 'hashlib', 'termios', 'socks', 'py_compile', 'difflib',
        'shlex', 'plistlib', 'tempfile', 'zipfile', 'fnmatch', 'calendar', 'logging',
        
        # Your Custom Modules
        'CalculateCorrelationMatrix',
        'CalculateCorrelations',
        'CalculatePC',
        'CalculateWellComparisons',
        'CalculateZoneAttributes',
        'Calculations',
        'ColorEdit',
        'ColumnSelectDialog',
        'ComboBoxDelegate',
        'CriteriaToZone',
        'CrossPlot',
        'DataLoadSegy',
        'DataLoadWellZone',
        'DataLoader',
        'DatabaseManager',
        'DateDelegate',
        'DecisionTreeDialog',
        'DeclineCurveAnalysis',
        'DefaultProperties',
        'DeleteZone',
        'DrawingArea',
        'EurNpv',
        'GunBarrel',
        'HighlightCriteriaDialog',
        'ImportExcel',
        'InZone',
        'LaunchCombinedCashflow',
        'LoadProductions',
        'ModelProperties',
        'Plot',
        'PlotTotals',
        'ProjectDialog',
        'ProjectOpen',
        'ProjectSaver',
        'PudWellSelector',
        'SaveDeclineCurveDialog',
        'ScenarioNameDialog',
        'SeisWare',
        'SeisWareConnect',
        'SwPropertiesEdit',
        'UiMain',
        'UiSetup',
        'WellProperties',
        'ZoneViewer',
        'numeric_table_widget_item',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['PyQt5', 'PyQt5.QtCore', 'PyQt5.QtGui', 'PyQt5.QtWidgets'], 
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=None,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=None)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='Map2',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,  # Change to False for a windowless application
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
